spring:
  application:
    name: migration-service
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_JDBC_URL}
    username: ${POSTGRES_JDBC_USERNAME}
    password: ${POSTGRES_JDBC_PASSWORD}
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
      auto-commit: false
  liquibase:
    change-log: db/changelog/master.yml