server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: directory-service
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_JDBC_URL}
    username: ${POSTGRES_JDBC_USERNAME}
    password: ${POSTGRES_JDBC_PASSWORD}