
spring:
  application:
    name: review-service
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_JDBC_URL}
    username: ${POSTGRES_JDBC_USERNAME}
    password: ${POSTGRES_JDBC_PASSWORD}
jwt:
  secretBase64: cXdlcXdlcXdlcXdlc2Rhc2VmdyB0MjM0ciBxMjRyZGZnZnNlcmc=
  expirationInMs: 86400000
server:
  port: 8083
